# -*- coding: utf-8 -*-
"""The_Healthcare_Policy_Navigator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_yyVqQFfyS6anSXAJj2CPl_wZW0wZRT
"""

# ==============================================================
# 🏥 Healthcare Policy Navigator (RAG Assistant)
# Gradio + Chroma + Embeddings + LLM
# ==============================================================

# --------------------------------------------------------------
# STEP 1 — Install Dependencies
# --------------------------------------------------------------
# !pip install gradio chromadb sentence-transformers pypdf transformers

# --------------------------------------------------------------
# STEP 2 — Import Libraries
# --------------------------------------------------------------
import gradio as gr
from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
import chromadb
from transformers import pipeline

# --------------------------------------------------------------
# STEP 3 — Load Embedding Model
# --------------------------------------------------------------
print("Loading embedding model...")
embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
print("Embedding model loaded")

# --------------------------------------------------------------
# STEP 4 — Initialize Vector Database (Chroma)
# --------------------------------------------------------------
client = chromadb.Client()

try:
    client.delete_collection("healthcare_docs")
except:
    pass

collection = client.create_collection("healthcare_docs")

# --------------------------------------------------------------
# STEP 5 — Load Language Model
# --------------------------------------------------------------
print("Loading LLM...")
llm = pipeline("text-generation", model="google/flan-t5-base")
print("LLM loaded successfully")

# --------------------------------------------------------------
# STEP 6 — Document Chunking
# --------------------------------------------------------------
def chunk_text(text, chunk_size=500, overlap=50):
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]
        chunks.append(chunk)
        start += chunk_size - overlap
    return chunks

# --------------------------------------------------------------
# STEP 7 — Process Uploaded PDF (Healthcare Regulation)
# --------------------------------------------------------------
def process_pdf(file):
    print("Processing PDF...")
    reader = PdfReader(file.name)
    text = ""
    for page in reader.pages:
        text += page.extract_text()
    chunks = chunk_text(text)
    print("Total chunks:", len(chunks))
    for i, chunk in enumerate(chunks):
        embedding = embedding_model.encode(chunk).tolist()
        collection.add(
            documents=[chunk],
            embeddings=[embedding],
            ids=[str(i)]
        )
    return f"Healthcare regulation processed successfully. {len(chunks)} chunks stored."

# --------------------------------------------------------------
# STEP 8 — Retriever
# --------------------------------------------------------------
def retrieve(query, k=3):
    query_embedding = embedding_model.encode(query).tolist()
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=k
    )
    docs = results["documents"][0]
    print("\nRetrieved Chunks:\n", docs)
    return docs

# --------------------------------------------------------------
# STEP 9 — Answer Generation
# --------------------------------------------------------------
def answer_question(query):
    docs = retrieve(query)
    context = " ".join(docs)
    prompt = f"""
You are a Healthcare Policy Navigator.

Use ONLY the context below to answer the question.

Context:
{context}

Question: {query}

Provide a short, clear, and actionable compliance answer for doctors, administrators, and IT staff.
"""
    response = llm(prompt, max_length=200, temperature=0.2)
    result = response[0]["generated_text"]
    print("\nRaw Model Output:\n", result)
    return result

# --------------------------------------------------------------
# STEP 10 — Chat Function
# --------------------------------------------------------------
def chat(question):
    if not question.strip():
        return "Please enter a question."
    answer = answer_question(question)
    if not answer:
        return "No answer generated."
    return answer

# --------------------------------------------------------------
# STEP 11 — Build Gradio Interface
# --------------------------------------------------------------
with gr.Blocks() as demo:
    gr.Markdown("# 🏥 Healthcare Policy Navigator (RAG Assistant)")

    gr.Markdown("""
Upload a healthcare regulation PDF and ask questions about:

• patient rights
• telemedicine data handling
• cross-border consultation rules
• penalties for violations
• compliance and enforcement
""")

    pdf_input = gr.File(label="Upload Healthcare Regulation PDF")
    upload_button = gr.Button("Process Regulation")
    status = gr.Textbox(label="Status")

    upload_button.click(process_pdf, inputs=pdf_input, outputs=status)

    question_box = gr.Textbox(label="Ask a Compliance Question")
    answer_box = gr.Textbox(label="Answer", lines=15)
    ask_button = gr.Button("Ask")

    ask_button.click(chat, inputs=question_box, outputs=answer_box)

# --------------------------------------------------------------
# STEP 12 — Launch Application
# --------------------------------------------------------------
demo.launch()

